.github/workflows/ci-admin-for-all.yaml
=> 管理コンソールのCI作成

.gitignore, docker-compose.yaml, infra/docker/infra/envoy/Dockerfile_development, infra/envoy/development.yaml
=> feature: Envoyの初期設定

.github/workflows/cd-admin-for-master.yaml, .github/workflows/cd-admin-for-release.yaml
=> fix: yarn global addしたものが実行できるように修正

.github/workflows/cd-admin-for-master.yaml, .github/workflows/cd-admin-for-release.yaml
=> fix: 静的ファイルがビルドされるよう修正

.github/workflows/ci-gateway-for-all.yaml
=> fix: gRPC-Gateway用のCIを修正

.github/workflows/ci-native-for-all.yaml
=> feat: ReactNative用のCI作成

.github/workflows/ci-native-for-all.yaml, README.md
=> feature: ReactNativeのCI周りの実装

.github/workflows/ci-native-for-all.yaml, native/.eslintrc.js, native/.prettierrc.js, native/babel.config.js, native/package.json, native/yarn.lock
差分が多すぎるのでここで一旦プルリクを🙇‍♂️
- [react-native-elements](https://github.com/react-native-elements/react-native-elements)の導入
- React NativeのEslintとPrettierの設定
- GitHub ActionsでLintが回るように修正
- EslintとPrettierのルールらへん
=> React Native Elementsの導入とEslintとPrettierの設定

api/hello/config/grpc.go, api/hello/internal/interface/grpc/v1/hello.go, api/hello/proto/hello_world.pb.go, api/hello/proto/hello_world_grpc.pb.go, docs/12_backend/11_swagger/apiv1.swagger.json, infra/gateway/proto/hello_world.pb.go, infra/gateway/proto/hello_world.pb.gw.go, infra/gateway/proto/hello_world_grpc.pb.go, proto/proto/hello_world.proto
=> feature: サンプルAPIいったん完成

.github/workflows/cron-merge-master-for-develop.yaml
* 開発用ブランチにMasterブランチの差分を自動マージするworkflowの作成
=> feat: 開発用ブランチにMasterブランチの差分を自動マージするworkflowの作成

Makefile, docker-compose.yaml, infra/docker/infra/grafana/Dockerfile, infra/docker/infra/prometheus/Dockerfile, infra/prometheus/development.yaml, native/yarn.lock
* モニタリング関連の初期設定
* Prometheus
* Grafana
* Makefileのコマンドを追加・修正
* make install したらyarn.lockも含まれちゃったので、変更が多くなってもた
=> feature: モニタリング関連の初期設定

.github/workflows/cron-merge-master-for-develop.yaml
=> feat: user_apiのcron処理を追加

Makefile
=> feat: Update Makefile

.github/workflows/cd-user-api-for-master.yaml, infra/docker/api/user/Dockerfile
=> feature: User APIのGithub Action設定

.github/workflows/cd-gateway-for-master.yaml, docker-compose.yaml, infra/docker/infra/gateway/Dockerfile, infra/gateway/config/environment.go, infra/gateway/config/exec.go, infra/gateway/config/grpc.go
* gRPC-Gatewayの設定を更新
* Github Actions用のコード作成
=> feature: gRPC-Gatewayの設定を更新

api/user/go.sum, api/user/internal/application/user.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/validation.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/infrastructure/validation/user.go, api/user/internal/interface/grpc/v1/error.go, api/user/registry/registry.go
=> feature: ユーザー登録APIの実装

native/package.json, native/yarn.lock
package.jsonに変更
僕の環境だとexpo立ち上がらなくて、少し変更させていただいた
=> fix: package.jsonの変更

api/user/internal/application/user.go, api/user/internal/domain/user/repository.go, api/user/internal/domain/user/service.go, api/user/internal/infrastructure/repository/user.go, api/user/internal/infrastructure/service/user.go, api/user/internal/interface/grpc/v1/user.go, api/user/lib/metadata/metadata.go
=> feature: ログインユーザー情報取得APIの実装

web/admin/app/components/organisms/SignInCard.vue, web/admin/app/components/organisms/SignInForm.vue, web/admin/app/components/templates/SignIn.vue, web/admin/app/layouts/default.vue, web/admin/app/pages/index.vue, web/admin/app/pages/signin.vue, web/admin/app/store/auth.ts, web/admin/app/types/forms/auth.ts
* サインイン画面のコンポーネント分割
* テストの実装
* サインイン画面のUI改修
* ユーザー情報の取得
* ロールによるログイン制限
* #45 の続き
* APIの実装を進めるために管理コンソールの一部を実装
=> refactor: サインイン画面のコンポーネント分割

api/user/config/logger.go, infra/gateway/config/logger.go
* ファイル出力だけでなく、コンソールログも出力するよう変更
=> feature: コンソールログも出力するよう変更

.github/workflows/cd-gateway-for-master.yaml, .github/workflows/cd-user-api-for-master.yaml, api/user/config/logger.go, infra/gateway/config/logger.go
=> feature: インフラ変更に伴うAPIの設定変更

infra/kubernetes/stg/gateway/nginx-deployment.yaml
=> feat: naginのマニフェスト作成

web/admin/app/components/molecules/TheAlert.vue, web/admin/app/components/templates/SignIn.vue, web/admin/app/pages/signin.vue
* ログインエラー時、アラート表示をするように
* 追加箇所のテストを作成
=> feat: ログインエラー時、アラート表示をするように

web/admin/app/components/molecules/TheAlert.vue, web/admin/app/components/templates/SignIn.vue, web/admin/app/pages/signin.vue, web/admin/spec/components/molecules/TheAlert.spec.ts, web/admin/spec/components/templates/SignIn.spec.ts
=> test: アラート表示関連のテスト作成

web/admin/app/components/molecules/TheAlert.vue, web/admin/app/components/organisms/CommonHeader.vue, web/admin/app/components/organisms/CommonSidebar.vue, web/admin/app/components/organisms/SettingsAccountList.vue, web/admin/app/components/organisms/SettingsProfileList.vue, web/admin/app/components/templates/Settings.vue, web/admin/app/components/templates/SignIn.vue, web/admin/app/pages/settings/index.vue, web/admin/app/pages/signin.vue, web/admin/app/store/auth.ts, web/admin/app/types/props/index.ts, web/admin/app/types/props/templates/Settings.ts, web/admin/app/types/props/templates/index.ts, web/admin/spec/components/molecules/TheAlert.spec.ts, web/admin/spec/components/organisms/CommonHeader.spec.ts, web/admin/spec/components/organisms/SettingsAccountList.spec.ts, web/admin/spec/components/organisms/SettingsProfileList.spec.ts, web/admin/spec/components/templates/Settings.spec.ts, web/admin/spec/components/templates/SignIn.spec.ts, web/admin/spec/store/auth.spec.ts
=> feature: [Admin] プロフィール編集画面のUI作成

.github/workflows/cd-admin-gateway-for-master.yaml, .github/workflows/cd-native-gateway-for-master.yaml, api/gateway/admin/package.json, api/gateway/native/package.json, api/server/user/internal/infrastructure/repository/user.go, infra/docker/api/gateway/admin/Dockerfile, infra/docker/api/gateway/native/Dockerfile, infra/docker/api/server/user/Dockerfile
=> feature: BFF用のコンテナ作成

api/gateway/admin/src/config/cors.ts, api/gateway/native/src/config/cors.ts
=> feat: プリフライトリクエストの許可を追加

api/gateway/admin/src/config/cors.ts, api/gateway/native/src/config/cors.ts
=> feat: CORSの設定

api/gateway/admin/src/lib/authenticated.ts, api/gateway/native/src/lib/authenticated.ts
=> fix: 認証の除外パスの見直し

api/gateway/admin/src/lib/authenticated.ts, api/gateway/native/src/lib/authenticated.ts
=> feat: OPTIONSメソッドのリクエストが来た時200を返すように

api/gateway/admin/src/index.ts, api/gateway/admin/src/lib/authenticated.ts, api/gateway/admin/src/routes/common.ts, api/gateway/admin/src/routes/index.ts, api/gateway/native/src/index.ts, api/gateway/native/src/lib/authenticated.ts, api/gateway/native/src/routes/common.ts, api/gateway/native/src/routes/index.ts
=> fix: プリフライトリクエスト周りの設定

.env.temp, docker-compose.yaml, infra/kubernetes/stg/gateway/nginx-configmap.yaml
=> feature: リバースプロキシコンテナの設定編集

api/gateway/admin/src/api/user.ts, api/gateway/admin/src/routes/v1/auth.ts, api/gateway/admin/src/types/input/user.ts, api/gateway/admin/src/types/request/auth.ts, api/gateway/native/src/api/user.ts, api/gateway/native/src/routes/v1/auth.ts, api/gateway/native/src/types/input/user.ts, api/gateway/native/src/types/request/auth.ts, docs/12_backend/11_swagger/admin.apiv1.yaml, docs/12_backend/11_swagger/native.apiv1.yaml
=> feature: ユーザー情報更新周りの実装

api/gateway/admin/src/routes/v1/auth.ts, api/gateway/admin/src/types/request/auth.ts, api/gateway/admin/src/types/response/auth.ts
=> fix: 不要なカラムの削除と必須項目に仮の値代入

api/server/user/internal/application/input/auth.go, api/server/user/internal/application/validation/auth_test.go
=> fix: base64周りのバリデーション修正

web/admin/app/components/atoms/TheFileInput.vue, web/admin/app/components/atoms/TheTextArea.vue, web/admin/app/components/organisms/SettingsEditProfileForm.vue, web/admin/app/components/templates/SettingsEditProfile.vue, web/admin/app/pages/settings/index.vue, web/admin/app/pages/settings/profile.vue, web/admin/app/plugins/vee-validate.ts, web/admin/app/store/auth.ts, web/admin/app/types/forms/auth.ts, web/admin/app/types/forms/utils.ts, web/admin/app/types/requests/auth.ts, web/admin/spec/components/atoms/TheFileInput.spec.ts, web/admin/spec/components/atoms/TheFormGroup.spec.ts, web/admin/spec/components/atoms/TheTextArea.spec.ts, web/admin/spec/components/organisms/SettingsEditEmailForm.spec.ts, web/admin/spec/components/organisms/SettingsEditPasswordForm.spec.ts, web/admin/spec/components/organisms/SettingsEditProfileForm.spec.ts, web/admin/spec/components/templates/SettingsEditProfile.spec.ts, web/admin/spec/helpers/response/auth.ts, web/admin/spec/store/auth.spec.ts
* プロフィール更新画面の実装
* プロフィール更新画面のテスト作成
=> feature: プロフィール更新画面の実装

api/gateway/admin/src/lib/authenticated.ts
=> fix: ヘルスチェック周りのバグ修正

native/app/screens/AccoutSetting.tsx
リストアイテムの書き方をちょっと変えてみた。
てかこれの書き方を統一したい！
=> fix: リストアイテムの書き方を変えた

api/server/user/internal/application/admin.go, api/server/user/internal/application/admin_test.go, api/server/user/internal/interface/grpc/v1/admin.go
=> feature: 管理者情報取得APIの実装

native/app/lib/util/ErrorUtil.tsx
=> lint: style

api/server/user/internal/application/admin.go, api/server/user/internal/application/admin_test.go, api/server/user/internal/domain/util.go, api/server/user/internal/infrastructure/repository/client.go, api/server/user/internal/infrastructure/repository/user.go, api/server/user/internal/infrastructure/service/user_test.go
=> fix: 管理者一覧取得APIの修正

web/admin/app/components/organisms/CommonSidebar.vue, web/admin/app/pages/admin/index.vue, web/admin/app/plugins/store-accessor.ts, web/admin/app/store/admin.ts, web/admin/app/store/auth.ts, web/admin/app/types/forms/admin.ts, web/admin/app/types/forms/index.ts, web/admin/app/types/props/templates/AdminList.ts, web/admin/app/types/props/templates/index.ts, web/admin/app/types/responses/admin.ts, web/admin/app/types/responses/index.ts, web/admin/app/types/store/admin.ts, web/admin/app/types/store/index.ts, web/admin/spec/components/organisms/CommonSidebar.spec.ts
* 管理者一覧画面のUI作成
* コンポーネントへの分割
* テストの作成
=> feature: 管理者一覧画面のUI作成

web/admin/app/components/atoms/TheSelect.vue, web/admin/app/components/organisms/AdminNewForm.vue, web/admin/app/components/templates/AdminList.vue, web/admin/app/pages/admin/index.vue, web/admin/app/store/admin.ts, web/admin/app/store/auth.ts, web/admin/app/store/common.ts, web/admin/app/types/forms/admin.ts, web/admin/app/types/forms/utils.ts, web/admin/app/types/requests/admin.ts, web/admin/app/types/requests/index.ts, web/admin/app/types/responses/admin.ts, web/admin/spec/components/atoms/TheSelect.spec.ts, web/admin/spec/components/organisms/AdminNewForm.spec.ts, web/admin/spec/components/templates/AdminList.spec.ts, web/admin/spec/helpers/response/admin.ts, web/admin/spec/helpers/response/index.ts, web/admin/spec/helpers/store-helper.ts, web/admin/spec/store/admin.spec.ts, web/admin/spec/store/auth.spec.ts, web/admin/spec/store/common.spec.ts
=> feature: 管理者登録周りの実装

web/admin/app/components/organisms/AdminListTable.vue, web/admin/app/components/organisms/SettingsEditEmailForm.vue, web/admin/app/components/organisms/SettingsEditPasswordForm.vue, web/admin/app/components/organisms/SettingsEditProfileForm.vue, web/admin/app/components/organisms/SignInForm.vue, web/admin/app/components/templates/AdminList.vue, web/admin/app/components/templates/SettingsEditEmail.vue, web/admin/app/components/templates/SettingsEditPassword.vue, web/admin/app/components/templates/SettingsEditProfile.vue, web/admin/app/components/templates/SignIn.vue, web/admin/app/pages/admin/index.vue, web/admin/app/pages/settings/email.vue, web/admin/app/pages/settings/password.vue, web/admin/app/pages/settings/profile.vue, web/admin/app/pages/signin.vue, web/admin/app/store/common.ts, web/admin/app/types/forms/auth.ts, web/admin/app/types/store/common.ts, web/admin/spec/components/organisms/AdminListTable.spec.ts
=> fix: APIへのリクエスト周りの修正

web/admin/app/store/admin.ts, web/admin/spec/components/organisms/SettingsEditEmailForm.spec.ts, web/admin/spec/components/organisms/SettingsEditPasswordForm.spec.ts, web/admin/spec/components/organisms/SettingsEditProfileForm.spec.ts, web/admin/spec/components/organisms/SignInForm.spec.ts, web/admin/spec/components/templates/SettingsEditEmail.spec.ts, web/admin/spec/components/templates/SettingsEditPassword.spec.ts, web/admin/spec/components/templates/SettingsEditProfile.spec.ts, web/admin/spec/components/templates/SignIn.spec.ts, web/admin/spec/helpers/response/admin.ts, web/admin/spec/store/admin.spec.ts, web/admin/spec/store/common.spec.ts
=> test: UI/UX変更に伴うテストの修正

api/server/user/internal/infrastructure/repository/user.go
=> fix: SELECT系のSQLを修正

native/package.json
* Prettier周りの設定
* Prettierでのリファクタ対象は以下で良いか確認
* ./app
* ./test
* コード見てるとPrettierで強制できていない気がしたのでこのプルリク作成した
* このプルリクマージされた後、誰か以下コマンドを実行しといて欲しい
> $ cd ./native && & yarn lint:fix
=> refactor: Prettier周りの設定

api/gateway/admin/src/api/admin.ts, api/gateway/admin/src/routes/v1/admin.ts, api/gateway/admin/src/types/input/admin.ts, api/server/user/internal/application/admin.go, api/server/user/internal/application/admin_test.go, api/server/user/internal/application/input/admin.go, api/server/user/internal/application/validation/admin.go, api/server/user/internal/application/validation/admin_test.go, api/server/user/internal/interface/grpc/v1/admin.go, api/server/user/mock/application/validation/admin.go, docs/12_backend/11_swagger/admin.apiv1.yaml
=> feature: 管理者検索用Protoの作成

api/gateway/native/src/api/user.ts, api/gateway/native/src/routes/v1/user.ts, api/gateway/native/src/types/output/user.ts, api/gateway/native/src/types/response/user.ts, docs/12_backend/11_swagger/native.apiv1.yaml
=> fix: Swaggerの修正

api/server/user/internal/domain/user/entity.go
=> fix: DB周りのバグの修正

api/gateway/admin/src/api/admin.ts, api/gateway/admin/src/routes/v1/admin.ts, api/server/book/internal/interface/grpc/v1/book.go, api/server/book/lib/array/convert.go, api/server/book/lib/array/convert_test.go, api/server/user/internal/infrastructure/repository/client.go, api/server/user/internal/interface/grpc/v1/admin.go, api/server/user/internal/interface/grpc/v1/auth.go, api/server/user/internal/interface/grpc/v1/user.go, api/server/user/lib/array/convert.go, api/server/user/lib/array/convert_test.go
=> fix: gRPCからの値の取得周りのコード修正

docs/12_backend/11_swagger/native.apiv1.yaml
=> docs: Update swagger

native/app/containers/AccountSetting.tsx, native/app/containers/index.ts, native/app/routes/UserInfoRoute.tsx, native/app/routes/index.tsx, native/app/screens/AccoutSetting.tsx, native/app/store/usecases/auth.ts, native/package.json, native/yarn.lock
* ログイン情報の再取得機能
* ログアウト機能
* スプラッシュ画面の作成
@Atsuhide ごめん、ここやっとかんと他がすすまんと思い実装してしまった
=> feature: アプリ再起動後もログイン情報が保持されるように

api/server/user/internal/application/admin.go, api/server/user/internal/application/admin_test.go, api/server/user/internal/application/auth.go, api/server/user/internal/application/auth_test.go, api/server/user/internal/application/user.go, api/server/user/internal/application/user_test.go, api/server/user/internal/domain/user/service.go, api/server/user/internal/infrastructure/repository/client.go, api/server/user/internal/infrastructure/service/user.go, api/server/user/internal/infrastructure/service/user_test.go, api/server/user/mock/domain/user/service.go
=> refactor: User APIのリファクタ

api/server/user/.golangci.yaml, api/server/user/internal/application/auth.go, api/server/user/internal/domain/user/repository.go, api/server/user/internal/domain/user/service.go, api/server/user/internal/infrastructure/repository/user.go, api/server/user/internal/infrastructure/service/user.go, api/server/user/mock/domain/user/repository.go, api/server/user/mock/domain/user/service.go
* OAuth認証を利用している時もユーザ情報が取得できるように修正
=> fix: OAuth認証を利用している時もユーザ情報が取得できるように

api/gateway/admin/src/lib/grpc-exception.ts, api/gateway/admin/src/lib/http-exception.ts, api/gateway/native/src/lib/http-exception.ts
=> refactor: 500のときエラー詳細をレスポンス内に含むように

api/server/user/internal/application/auth.go
=> refactor: 未使用コードの削除

api/gateway/admin/src/api/admin.ts, api/gateway/admin/src/routes/v1/admin.ts, api/gateway/admin/src/types/input/admin.ts, api/gateway/admin/src/types/output/admin.ts, api/gateway/admin/src/types/response/admin.ts
=> feature: 管理者サムネイルアップロード用のエンドポイントを実装

api/server/user/internal/application/admin.go, api/server/user/internal/application/input/admin.go, api/server/user/internal/application/validation/admin.go, api/server/user/internal/application/validation/admin_test.go, api/server/user/internal/interface/grpc/v1/admin.go, api/server/user/mock/application/validation/admin.go
=> feature: 管理者のサムネアップロードAPIの実装

api/gateway/admin/src/api/admin.ts, api/gateway/admin/src/routes/v1/admin.ts, api/gateway/admin/src/types/input/admin.ts
=> feature: 管理者削除エンドポイントの作成

api/gateway/admin/src/api/admin.ts, api/gateway/admin/src/routes/v1/admin.ts, api/gateway/admin/src/types/input/admin.ts, docs/12_backend/11_swagger/admin.apiv1.yaml
=> feature: 管理者情報取得エンドポイントの作成

api/gateway/admin/src/api/index.ts, api/gateway/admin/src/index.ts, api/gateway/admin/src/routes/index.ts, api/gateway/admin/src/routes/v1/book.ts
=> refactor: Admin BFFの不足コード追加

api/gateway/native/src/index.ts, api/gateway/native/src/routes/index.ts, api/gateway/native/src/routes/v1/book.ts, api/gateway/native/src/routes/v1/bookshelf.ts, docs/12_backend/11_swagger/native.apiv1.yaml
=> fix: 書籍関連APIのPATHを修正

api/gateway/native/src/api/book.ts, api/gateway/native/src/routes/v1/bookshelf.ts, api/gateway/native/src/types/input/book.ts
=> faeture: 本棚削除エンドポイントの作成

api/server/user/internal/application/auth.go, api/server/user/internal/application/auth_test.go, api/server/user/internal/application/input/auth.go, api/server/user/internal/application/validation/auth.go, api/server/user/internal/application/validation/auth_test.go, api/server/user/internal/interface/grpc/v1/auth.go, api/server/user/mock/application/validation/auth.go
=> fature: デバイス登録APIの実装

api/server/user/internal/application/admin.go, api/server/user/internal/application/admin_test.go, api/server/user/internal/interface/grpc/v1/admin.go
=> feature: 管理者権限削除APIの実装

api/server/book/internal/application/book.go, api/server/book/internal/application/book_test.go, api/server/book/internal/domain/book/repository.go, api/server/book/internal/domain/book/service.go, api/server/book/internal/infrastructure/repository/book.go, api/server/book/internal/infrastructure/service/book.go, api/server/book/internal/infrastructure/service/book_test.go, api/server/book/internal/interface/grpc/v1/book.go, api/server/book/mock/domain/book/repository.go, api/server/book/mock/domain/book/service.go
=> feature: 書籍削除APIの実装

api/gateway/admin/src/api/user.ts, api/gateway/admin/src/routes/v1/user.ts, api/server/user/internal/application/input/user.go, api/server/user/internal/application/user.go, api/server/user/internal/application/user_test.go, api/server/user/internal/application/validation/user.go, api/server/user/internal/application/validation/user_test.go, api/server/user/internal/interface/grpc/v1/user.go, api/server/user/mock/application/validation/user.go
=> feature: ユーザー一覧取得APIの実装

api/server/user/internal/application/user.go
=> fix: ユーザー一覧取得APIの修正

api/gateway/native/src/api/user.ts, api/gateway/native/src/types/input/user.ts, api/gateway/native/src/types/output/user.ts
=> feature: ユーザー一覧取得用メソッドの作成

api/gateway/admin/src/index.ts, api/gateway/admin/src/routes/v1/admin.ts, api/gateway/admin/src/routes/v1/auth.ts, api/gateway/admin/src/routes/v1/book.ts, api/gateway/admin/src/routes/v1/user.ts, api/gateway/native/src/index.ts, api/gateway/native/src/routes/v1/book.ts, api/server/book/internal/domain/book/repository.go, api/server/book/internal/infrastructure/repository/book.go, api/server/book/internal/infrastructure/service/book.go, api/server/book/internal/infrastructure/service/book_test.go, api/server/book/mock/domain/book/repository.go
=> refactor: 書籍API周りのリファクタ

web/admin/app/components/organisms/CommonSidebar.vue, web/admin/app/components/templates/Debug.vue, web/admin/app/pages/debug.vue, web/admin/app/store/auth.ts, web/admin/package.json, web/admin/spec/components/organisms/CommonSidebar.spec.ts, web/admin/spec/components/templates/Debug.spec.ts, web/admin/spec/store/auth.spec.ts, web/admin/yarn.lock
=> feature: 検証用ページの作成

web/admin/app/components/atoms/TheFileInput.vue, web/admin/app/components/organisms/SettingsEditProfileForm.vue, web/admin/app/pages/settings/profile.vue, web/admin/app/store/auth.ts, web/admin/app/types/forms/auth.ts, web/admin/app/types/requests/auth.ts, web/admin/app/types/responses/auth.ts, web/admin/spec/components/atoms/TheFileInput.spec.ts, web/admin/spec/components/organisms/SettingsEditProfileForm.spec.ts, web/admin/spec/components/templates/SettingsEditProfile.spec.ts, web/admin/spec/helpers/response/auth.ts, web/admin/spec/helpers/response/index.ts, web/admin/spec/store/auth.spec.ts
=> feature: プロフィール編集機能の更新

web/admin/app/components/organisms/AdminEditForm.vue, web/admin/app/components/templates/AdminList.vue, web/admin/app/pages/admin/index.vue
* 管理者情報編集画面のUI実装
* 型定義
* APIとの連携
* テストの作成
* 差分が多いのでいったんプルリク出します
=> feature: 管理者情報編集画面のUI実装

web/admin/app/components/organisms/AdminEditForm.vue, web/admin/app/components/organisms/AdminNewForm.vue, web/admin/app/components/templates/AdminList.vue, web/admin/app/pages/admin/index.vue, web/admin/app/types/forms/admin.ts
* 管理者情報編集機能の型定義
* APIとの連携
* テストの作成
* #257 (feature: 管理者情報編集画面のUI実装) の続き
=> feature: 管理者情報編集機能の型定義

web/admin/app/components/organisms/AdminListTable.vue, web/admin/app/components/templates/AdminList.vue, web/admin/app/pages/admin/index.vue, web/admin/app/store/auth.ts, web/admin/spec/components/organisms/AdminListTable.spec.ts, web/admin/spec/components/templates/AdminList.spec.ts, web/admin/spec/store/auth.spec.ts
=> feature: 管理者一覧画面の編集

web/admin/app/components/atoms/TheFileInput.vue, web/admin/app/components/organisms/AdminEditForm.vue, web/admin/app/components/organisms/SettingsEditProfileForm.vue, web/admin/app/components/templates/AdminList.vue, web/admin/app/pages/admin/index.vue, web/admin/app/pages/settings/profile.vue, web/admin/app/plugins/vee-validate.ts, web/admin/app/store/auth.ts, web/admin/app/types/forms/admin.ts, web/admin/app/types/forms/auth.ts, web/admin/spec/components/atoms/TheFileInput.spec.ts, web/admin/spec/components/organisms/SettingsEditProfileForm.spec.ts, web/admin/spec/components/templates/SettingsEditProfile.spec.ts, web/admin/spec/store/auth.spec.ts
=> fix: ファイルインプット関連の修正

web/admin/app/pages/admin/index.vue, web/admin/app/store/admin.ts, web/admin/app/types/requests/admin.ts, web/admin/app/types/responses/admin.ts
* 管理者情報編集機能の実装
* async/await周りの処理
* テストコードの作成
* リクエスト値変えたのでAPIの修正
* #257 feature: 管理者情報編集画面のUI実装 の続き
* #258 feature: 管理者情報編集機能の型定義 の続き
=> feature: 管理者情報編集機能の実装

docker-compose.yaml, infra/docker/api/server/information/Dockerfile, infra/docker/api/server/information/Dockerfile_development
=> Feature: notification apiのdocker設定

api/gateway/admin/src/lib/grpc-metadata.ts, api/gateway/native/src/lib/grpc-metadata.ts, api/server/book/config/grpc.go, api/server/information/config/grpc.go, api/server/user/config/grpc.go, infra/kubernetes/stg/gateway/nginx-configmap.yaml, infra/nginx/staging.conf
=> feature: ログ周りのリファクタ

docs/12_backend/11_swagger/admin.apiv1.yaml
=> Feature: information swaggerの設定

native/app/components/organisms/BookImpression.tsx, native/app/components/organisms/BookInfo.tsx, native/app/screens/BookShow.tsx, native/app/store/usecases/book.ts, native/app/types/forms/index.ts, native/app/types/navigation/index.ts, native/app/types/response/book.ts
- 書籍の感想一覧を取得し表示
一部、lintが効いてなくて変なファイルの書き換えも入ってます🙏
APIのレスポンス構造について @taba2424 と詰める
=> feature: 感想一覧の表示とUI調整

native/app/routes/UserInfoRoute.tsx, native/app/screens/AccoutSetting.tsx, native/app/screens/BookShowImpressionParent.tsx, native/app/screens/Messages.tsx, native/app/screens/MyPage.tsx, native/app/screens/SignUp.tsx, native/app/types/forms/index.ts, native/test/components/atoms/BackIcon.test.tsx, native/test/components/atoms/CloseIcon.test.tsx, native/test/components/atoms/HeaderText.test.tsx
- `develop/native`でlint/prettierが当たっていない部分があったので当てた。
=> refactor: Lint/Prettierが当たっていない部分を修正

infra/server/bin/update-certificate.sh.temp
* 証明書更新用スクリプトの修正
* 証明書更新後、アプリケーションの再起動処理を追加
* 更新後の証明書を Nginx へ適用するよう設定修正
=> fix: 証明書更新用スクリプトの修正

native/app/components/molecules/ProfileBasicInfoGroup.tsx, native/app/components/molecules/ProfileFollowFollower.tsx, native/app/components/organisms/ChangeNickname.tsx, native/app/components/organisms/GenderRadioGroup.tsx, native/app/routes/UserInfoRoute.tsx, native/app/screens/MyPage.tsx, native/app/screens/OwnProfile.tsx, native/app/screens/ProfileEdit.tsx
- #307 の対応
- マイページタブのメニューのテキスト色などの修正
#313 の対応
=> fix: nativeアプリのマイページタブの部分の修正

api/gateway/native/src/routes/v1/chat.ts, api/gateway/native/src/types/response/chat.ts
=> fix: タイポの修正

api/server/information/config/grpc.go, api/server/information/internal/infrastructure/validation/notification.go, api/server/information/registry/registry.go
* Notification Serviceの起動設定
* Notification ServiceのDI周りの設定
=> feature: Notification Serviceの起動設定

.github/labeler.yaml, .github/reviewer.yaml, .github/workflows/pr-approve.yaml, .github/workflows/pr-labeler.yaml, .github/workflows/pr-reviewer.yaml
* Github Actionsのワークフローを追加
* レビュアーの自動追加
* ラベルの自動付与
* Approveされたのが分かるようにラベル追加
=> feature: Github Actionsのワークフローを追加

docs/12_backend/11_swagger/native.apiv2.yaml
* 書籍API周りのSwagger更新
* /v2として書籍取得APIの仕様を定義
=> docs: 書籍API周りのSwagger更新

api/gateway/native/src/routes/v2/bookshelf.ts
* 本棚の書籍取得API(v2)の作成
* クエリ (key) 指定で id, isbn どちらで取得できるか選択できるようにしました
* async/await周りのネストをなんとかしたい...
* bookID指定での取得, ISBN指定での取得の使い分けについては、↓のようにクエリパラメータをしていしてもらえればと
* bookID指定: `http://localhost:8080/v2/users/{userId}/books/{bookId}?key=id`
* ISBN指定: `http://localhost:8080/v2/users/{userId}/books/{isbn}?key=isbn`
* ちなみに、クエリパラメータ (key) のデフォルト値については、idにしてるので🙇‍♂️
* APIのレスポンス取得例としては↓のようになるようにしてる!!
* 変更あれば言っていただければと🙇‍♂️
* bookshelf が undefined で返ってくる
```json
{
"id": 4,
"title": "ちはやふる（4）",
"titleKana": "チハヤフル4",
"description": "",
"isbn": "9784063192599",
"publisher": "講談社",
"publishedOn": "2009年03月",
"thumbnailUrl": "https://thumbnail.image.rakuten.co.jp/@0_mall/book/cabinet/2599/9784063192599.jpg?_ex=200x200",
"rakutenUrl": "https://books.rakuten.co.jp/rb/5996499/",
"size": "コミック",
"author": …
```
=> feature: 本棚の書籍取得API(v2)の作成

api/gateway/native/src/index.ts, api/gateway/native/src/routes/index.ts, api/gateway/native/src/routes/v2/book.ts, api/gateway/native/src/types/response/index.ts, api/gateway/native/src/types/response/v2/book.ts, docs/12_backend/11_swagger/native.apiv2.yaml
* 書籍取得API(v2)の作成
* レスポンスにユーザ固有の情報を持たせないように
* レビュー一覧の追加
* async/await周りでネストが深くなっていた箇所のリファクタ
* リクエストを投げる際のパラメータについては、本棚の書籍取得API(v2)と同じ仕様にしてます
* https://github.com/calmato/gran-book/pull/332#issue-687284203
* レスポンスとしては以下のようなものが返るよう修正してます
```json
{
"id": 1,
"title": "ちはやふる（46）",
"titleKana": "チハヤフル46",
"description": "",
"isbn": "9784065225608",
"publisher": "講談社",
"publishedOn": "2021年03月12日",
"thumbnailUrl": "https://thumbnail.image.rakuten.co.jp/@0_mall/book/cabinet/5608/9784065225608.jpg?_ex=200x200",
"rakutenUrl": "https://books.rakuten.co.jp/rb/16609483/",
"size": "コミック",
"author": "末次 由紀",
"authorKana": "スエツグ ユキ",
"createdAt": "2021-07-10 12:52:49",
"updatedAt": "2021-07-10 12:52:49",
"reviews": [
{
"id": 1,
"impression": "BloomRPCの使い方がわかりやすかったです",
"createdAt": "2021-07-10 12:56:11", …
```
=> feature: 書籍取得API(v2)の作成

infra/kubernetes/stg/gateway/nginx-configmap.yaml, infra/kubernetes/stg/logging/fluent-bit-configmap.yaml, infra/nginx/nginx.conf
=> fix: Nginxのコンフィグを修正

api/server/book/internal/domain/exception/validation.go, api/server/information/internal/domain/exception/validation.go, api/server/user/internal/domain/chat/entity.go, api/server/user/internal/domain/exception/validation.go, docs/99_other/README.md
=> fix: typo - massage -> message

.github/workflows/cd-swagger.yaml, docs/14_infrastructure/33_virtual_machine/README.md, infra/server/README.md, infra/server/bin/ubuntu-setup.sh, infra/server/bin/update-certificate.sh.temp, infra/server/html/index.html
* 管理用サーバでSwagger UIサーバを起動するように
* サーバに設定している内容のドキュメント化
* cronjob設定で、masterブランチの内容を定期的にPullするように設定する
=> feat: 管理用サーバでSwagger UIサーバを起動するように

web/admin/app/components/organisms/BookMultipleRegister.vue, web/admin/app/components/templates/BookList.vue
書籍の一括登録UIの実装をした。
csv登録後、DBに登録されるようにする
=> Feat: 書籍一括登録のUI実装

native/app/components/atoms/HeaderText.tsx, native/app/components/atoms/ProfileNumberOfThings.tsx, native/app/components/molecules/ForgotPasswordButton.tsx, native/app/components/organisms/FlexBoxBookCategory.tsx, native/app/components/organisms/GenderRadioGroup.tsx, native/app/components/organisms/ReadDate.tsx, native/app/routes/ServiceRoute.tsx, native/app/screens/SignInSelect.tsx, native/constants/theme.ts
[https://github.com/calmato/gran-book/pull/346](url)
で抜けていた部分へのFONT_SIZE適用
constants/theme.ts内の
`Button`に`FONT_SIZE.BUTTON_DEFAULT`を適用して問題ないか
=> style: FONT_SIZE適用

api/server/book/internal/infrastructure/repository/book.go
* 書籍登録時、著者情報を取得していないことで500エラーを吐いていたため修正
@sea-kai が見つけてくれたバグの修正になります!
=> fix: create book db operation

.github/workflows/ci-user-api-for-all.yaml, api/server/user/.gitignore, api/server/user/Makefile, api/server/user/config/exec.go, api/server/user/internal/domain/user/entity.go, api/server/user/internal/infrastructure/repository/user.go, api/server/user/internal/infrastructure/repository/user_test.go, api/server/user/pkg/database/client.go, api/server/user/pkg/test/api.go, api/server/user/pkg/test/database.go, api/server/user/pkg/test/env.go, api/server/user/pkg/test/mock.go
=> feat: add test code in user repository

.github/workflows/ci-book-api-for-all.yaml, .github/workflows/ci-user-api-for-all.yaml, api/server/book/.gitignore, api/server/book/Makefile, api/server/book/config/exec.go, api/server/book/internal/domain/book/entity.go, api/server/book/internal/infrastructure/repository/book.go, api/server/book/internal/infrastructure/repository/book_test.go, api/server/book/pkg/database/client.go, api/server/book/pkg/test/database.go, infra/mysql/sql/01-create.sql
=> feat: add test code in book repository

api/server/user/internal/application/user.go
* ユーザー登録時、IDがnilで500になっているバグを修正
=> fix: add parameter in user

api/server/book/internal/infrastructure/repository/book.go, api/server/book/internal/infrastructure/repository/book_test.go, api/server/book/pkg/datetime/format.go, api/server/book/pkg/datetime/format_test.go
* 本棚へ読んだ本を登録する際に起こる `time.Time型のZero値 -> 0000-00-00 として登録される` バグを修正
* トランザクションをロールバックしやすいようにリファクタ (実際の登録/更新処理をプライベートメソッドとして切り出し)
=> fix: fix book repository

native/.eslintignore, native/.prettierignore, native/app/hooks/usePrepare.ts, native/app/screens/NotificationMessage.tsx, native/app/types/response/chat.ts
Protoから自動生成されたファイルが追加されたことに伴い、lintのignore設定を追加しました
=> feat: Lint周りの設定編集

native/jest.config.js, native/package.json
=> feat: Jestの設定

web/admin/jest.config.js, web/admin/package.json
=> feat: Jest周りの設定編集

native/package.json
=> feat: update package.json

api/gateway/native/internal/server/v1/top.go
=> fix: fix context

api/gateway/native/internal/server/v1/top.go, api/gateway/native/pkg/datetime/jst.go, api/gateway/native/pkg/datetime/jst_test.go
=> fix: datetime format

api/gateway/native/internal/entity/top.go, api/gateway/native/internal/entity/top_test.go, api/gateway/native/internal/server/v1/top.go
* 読んだ本の実績のレスポンスで12ヶ月分の情報を返していなかったのを修正
=> fix: top user response

api/server/book/internal/infrastructure/repository/book.go, api/server/book/internal/infrastructure/repository/book_test.go, api/server/user/internal/infrastructure/repository/user.go, api/server/user/internal/infrastructure/repository/user_test.go
=> refactor: table name

api/gateway/native/internal/request/v1/auth.go, api/gateway/native/internal/server/v1/auth.go, api/gateway/native/internal/server/v1/auth_test.go, api/gateway/native/pkg/test/api.go
=> feat: add auth test in native gateway

api/gateway/native/internal/response/v1/bookshelf_test.go, api/gateway/native/internal/response/v1/chat.go, api/gateway/native/internal/response/v1/chat_test.go, api/gateway/native/internal/response/v1/review_test.go
=> feat: improvement coverage in native gateway

api/gateway/native/Makefile, api/gateway/native/internal/entity/book_test.go, api/gateway/native/internal/entity/bookshelf_test.go, api/gateway/native/internal/entity/chat_test.go, api/gateway/native/internal/entity/common.go, api/gateway/native/internal/entity/common_test.go, api/gateway/native/internal/entity/exception_test.go, api/gateway/native/internal/entity/review_test.go, api/gateway/native/internal/entity/top_test.go, api/gateway/native/internal/entity/user_test.go, api/gateway/native/internal/response/v2/book_test.go, api/gateway/native/internal/response/v2/bookshelf_test.go, api/gateway/native/pkg/array/contains.go, api/gateway/native/pkg/array/contains_test.go, api/gateway/native/pkg/array/convert.go, api/gateway/native/pkg/array/convert_test.go
=> feat: add test code

api/gateway/native/internal/server/router.go
=> fix: native gateway routes

web/admin/yarn.lock
=> chore: update package.json
